Repository javier-aguilar/drag-time-api, pull requests merged in 2020-07, with the labels that each got.

#4 Create pull_request_template.md
  .github/pull_request_template.md
Labels: Phase 1

#15 User Can See List Of Events (BE)
  .github/workflows/elixir.yml
  config/prod.exs
  config/prod.secret.exs
  config/test.exs
  elixir_buildpack.config
  lib/drag_time_api/artists.ex
  lib/drag_time_api/artists/artist.ex
  lib/drag_time_api/events.ex
  lib/drag_time_api/events/event.ex
  lib/drag_time_api/events_artists/events_artists.ex
  lib/drag_time_api/locations.ex
  lib/drag_time_api/locations/location.ex
  lib/drag_time_api_web/controllers/artist_controller.ex
  lib/drag_time_api_web/controllers/event_controller.ex
  lib/drag_time_api_web/controllers/fallback_controller.ex
  lib/drag_time_api_web/controllers/location_controller.ex
  lib/drag_time_api_web/router.ex
  lib/drag_time_api_web/views/artist_view.ex
  lib/drag_time_api_web/views/changeset_view.ex
  lib/drag_time_api_web/views/event_view.ex
  lib/drag_time_api_web/views/location_view.ex
  mix.exs
  mix.lock
  phoenix_static_buildpack.config
  priv/repo/migrations/20200719143621_create_locations.exs
  priv/repo/migrations/20200719143840_create_events.exs
  priv/repo/migrations/20200719202643_create_artists.exs
  priv/repo/migrations/20200719203300_create_events_artists.exs
  priv/repo/seeds.exs
  test/drag_time_api/artists_test.exs
  test/drag_time_api/events_test.exs
  test/drag_time_api/locations_test.exs
  test/drag_time_api_web/controllers/artist_controller_test.exs
  test/drag_time_api_web/controllers/event_controller_test.exs
  test/drag_time_api_web/controllers/location_controller_test.exs
Labels: BE, Phase 2

#20 Deployment of Back-End to Heroku
  Procfile
  elixir_buildpack.config
  phoenix_static_buildpack.config
Labels: BE

#21 Update CORS Config
  lib/drag_time_api_web/router.ex
  lib/drag_time_api_web/views/event_view.ex
  mix.exs
  mix.lock
Labels: BE

#22 Tb test
  test/drag_time_api/artists_test.exs
  test/drag_time_api/events_artists_test.exs
  test/drag_time_api/locations_test.exs
  test/drag_time_api_web/controllers/artist_controller_test.exs
  test/drag_time_api_web/controllers/location_controller_test.exs
Labels: BE, Testing
